notifications:
  email: false
language: node_js
node_js:
  - '6.9.1'
  - node
sudo: true
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - npm install buffer-shims
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
